theme: jekyll-theme-cayman
title: News Daily
description: AI-curated daily digest of politics, business, and world news
baseurl: "/horizon-private" # the subpath of your site, e.g. /blog
url: "https://xxxco.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
future: true # Allow future posts to be published
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - ".github"
  - "node_modules"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
